name: chamet_mvp
description: Minimal Flutter app to test real-time video via Jitsi
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
